framework:
    secret: '%env(APP_SECRET)%'
    #default_locale: en
    #csrf_protection: ~
    #http_method_override: true
    #trusted_hosts: ~
    session:
        handler_id: ~
    #esi: ~
    #fragments: ~
    php_errors:
        log: true
